apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if eq .Values.cloud "aws" }}
    eks.amazonaws.com/role-arn: {{ .Values.api.serviceAccount.awsRoleArn }}
    {{- end }}
    {{- if eq .Values.cloud "azure" }}
    azure.workload.identity/client-id: {{ .Values.api.serviceAccount.azureClientId }}
    azure.workload.identity/use: "true"
    {{- end }}
