{{- $root := . -}}
{{- $pools := include "braintrust.apiPools" . | fromYamlArray -}}
{{- range $index, $pool := $pools }}
{{- if gt $index 0 }}
---
{{- end }}
{{ include "braintrust.apiDeployment" (dict "root" $root "api" $pool.config "role" $pool.role) }}
{{- end }}
