apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  namespace: {{ include "braintrust.namespace" . }}
  {{- with (merge .Values.global.labels .Values.api.labels) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    {{- if eq .Values.cloud "aws" }}
    eks.amazonaws.com/role-arn: {{ .Values.api.serviceAccount.awsRoleArn }}
    {{- end }}
    {{- if eq .Values.cloud "azure" }}
    azure.workload.identity/client-id: {{ .Values.api.serviceAccount.azureClientId }}
    {{- end }}
    {{- with .Values.api.annotations.serviceaccount }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
