apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.brainstore.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if eq .Values.cloud "aws" }}
    eks.amazonaws.com/role-arn: {{ .Values.brainstore.serviceAccount.awsRoleArn }}
    {{- end }}
    {{- if eq .Values.cloud "azure" }}
    azure.workload.identity/client-id: {{ .Values.brainstore.serviceAccount.azureClientId }}
    {{- end }}
