apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.brainstore.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "apps.service-labels" (dict "context" . "service" .Values.brainstore) | nindent 4 }}
  annotations:
    {{- if eq .Values.cloud "aws" }}
    eks.amazonaws.com/role-arn: {{ .Values.brainstore.serviceAccount.awsRoleArn }}
    {{- end }}
    {{- if eq .Values.cloud "azure" }}
    azure.workload.identity/client-id: {{ .Values.brainstore.serviceAccount.azureClientId }}
    {{- end }}
    {{- if eq .Values.cloud "google" }}
    iam.gke.io/gcp-service-account: {{ .Values.brainstore.serviceAccount.googleServiceAccount }}
    {{- end }}
    {{- with .Values.brainstore.annotations.serviceaccount }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
