{{- include "braintrust.loopRuntime.validate" . -}}
{{- if .Values.loopRuntime.enabled -}}
{{- $labels := mergeOverwrite (deepCopy .Values.global.labels) (deepCopy .Values.loopRuntime.labels) -}}
{{- $annotations := deepCopy .Values.loopRuntime.annotations.serviceaccount -}}
{{- if and (eq .Values.cloud "aws") .Values.loopRuntime.serviceAccount.awsRoleArn -}}
{{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.loopRuntime.serviceAccount.awsRoleArn -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.loopRuntime.serviceAccount.name }}
  namespace: {{ include "braintrust.namespace" . }}
  {{- with $labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
