apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    {{- if eq .Values.cloud "azure" }}
    azure.workload.identity/use: "true"
    {{- end }}
    {{- with (merge .Values.global.labels .Values.global.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.annotations.namespaces }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
