{{- if .Values.azureKeyVaultCSI }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.azureKeyVaultCSI.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: braintrust-secrets
    type: Opaque
    data:
      {{- range .Values.azureKeyVaultCSI.secrets }}
      - key: {{ .kubernetesSecretKey }}
        objectName: {{ .keyVaultSecretName }}
      {{- end }}
  parameters:
    usePodIdentity: "false"
    keyvaultName: "{{ .Values.azureKeyVaultCSI.name }}"
    clientID: "{{ .Values.azureKeyVaultCSI.clientID }}"
    tenantId: "{{ .Values.azureKeyVaultCSI.tenantId }}"
    objects: |
      array:
        {{- range .Values.azureKeyVaultCSI.secrets }}
        - |
          objectName: {{ .keyVaultSecretName }}
          objectType: {{ .keyVaultSecretType }}
        {{- end }}
{{- end }}