{{- if and (eq .Values.cloud "azure") .Values.azure.enableAzureKeyVaultDriver }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.azure.keyVaultName }}
  namespace: {{ include "braintrust.namespace" . }}
  {{- with .Values.global.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: azure
  secretObjects:
  - secretName: braintrust-secrets
    type: Opaque
    data:
      {{- range .Values.azureKeyVaultDriver.secrets }}
      - key: {{ .kubernetesSecretKey }}
        objectName: {{ .keyVaultSecretName }}
      {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: "{{ .Values.azure.keyVaultName }}"
    clientID: "{{ .Values.azure.keyVaultCSIclientID }}"
    tenantId: "{{ .Values.azure.tenantId }}"
    objects: |
      array:
        {{- range .Values.azureKeyVaultDriver.secrets }}
        - |
          objectName: {{ .keyVaultSecretName }}
          objectType: {{ .keyVaultSecretType }}
        {{- end }}
{{- end }}
